language: generic
dist: trusty

env:
  global:
    # For pushing documentation
    - ENCRYPTION_LABEL: "388c738922bf"
    - COMMIT_AUTHOR_EMAIL: "topisani@hamsterpoison.com"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:

    # Linux, Clang 7, Debug, libc++
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++-7-abi-dev
            - gdb-minimal
            - libgles2-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - CC=clang-7 CXX=clang++-7
        - BUILD_TYPE=Debug
        - USE_LIBCXX=1
        - DEPLOY_DOCS=1

    # Linux, GCC, Debug, libstdc++
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gdb-minimal
            - libjack-jackd2-dev
            - libgles2-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - CC=gcc-7 CXX=g++-7
        - BUILD_TYPE=Debug
        - USE_LIBCXX=0

    # OSX, GCC, Debug, libc++
    - os: osx
      osx_image: xcode9.1
      env:
        - CC=clang CXX=clang++
        - MATRIX_EVAL="brew update; brew install gdb llvm"
        - LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
        - PATH="/usr/local/opt/llvm/bin:$PATH"
        - USE_LIBCXX=1

before_install:
  - eval $MATRIX_EVAL

install:
  - $CXX --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  # Install cmake
  - CMAKE_VERSION=3.9.2
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - export CXXFLAGS="$CXXFLAGS -Werror"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOTTO_USE_LIBCXX=$USE_LIBCXX $CMAKE_OPTIONS

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake --build build -- -j${JOBS}
  - |
    [[ "$DEPLOY_DOCS" == "1" ]] && script/deploy-docs
  - build/bin/test -s || RESULT=$?
    if [[ -n "$RESULT" ]]; then
    echo "Tests failed, running in GDB for stacktrace"
    gdb -return-child-result -batch -ex "run -s" -ex "thread apply all bt" -ex "quit" --args build/bin/test
    fi

notifications:
  email: false
